// src/pages/CheckInPage.tsx
import { useState } from 'react';
import NavBar from '@/components/common/NavBar';
import { useStore } from '@/store/useStore';

export default function CheckInPage() {
  const [animating, setAnimating] = useState(false);
  const [displayCount, setDisplayCount] = useState(0);
  const checkInDays = useStore((s) => s.checkInDays);
  const lastCheckInDate = useStore((s) => s.lastCheckInDate);
  const checkIn = useStore((s) => s.checkIn);
  const showToast = useStore((s) => s.showToast);
  const isVerified = useStore((s) => s.isVerified);
  const setShowVerifyModal = useStore((s) => s.setShowVerifyModal);

  const today = new Date().toISOString().split('T')[0];
  const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
  const checkedInToday = lastCheckInDate === today;
  // 是否连续签到（昨日签到过）
  const isContinuous = lastCheckInDate === yesterday;
  // 断签时基础显示为 0（与原逻辑一致），已签到或连续时显示 store 中的天数
  const baseCount = checkedInToday || isContinuous ? checkInDays : 0;

  const handleCheckIn = () => {
    if (!isVerified) {
      setShowVerifyModal(true);
      return;
    }
    if (animating || checkedInToday) return;
    setAnimating(true);
    // 目标值：连续则 +1，断签则重置为 1
    const target = isContinuous ? checkInDays + 1 : 1;
    let current = baseCount;
    setDisplayCount(current);
    const timer = setInterval(() => {
      current += 1;
      if (current >= target) {
        clearInterval(timer);
        checkIn();
        setDisplayCount(target);
        setAnimating(false);
        showToast('签到成功', 'success');
      } else {
        setDisplayCount(current);
      }
    }, 100);
  };

  // 动画中显示 displayCount，否则显示 baseCount
  const count = animating ? displayCount : baseCount;
  const digits = String(count).padStart(3, '0').split('');

  return (
    <div className="page-container bg-neu-bg">
      <NavBar title="签到活动" />

      {/* 主签到卡片 */}
      <div className="mx-4 mt-4">
        <div className="neu-raised rounded-lg-card p-6 flex flex-col items-center">
          <p className="text-sm text-neu-text-muted font-semibold mb-4">
            {checkedInToday ? '今日已签到' : '已连续签到'}
          </p>

          {/* 数字翻牌计数器 */}
          <div className="flex items-center gap-2 mb-6">
            {digits.map((d, i) => (
              <div
                key={i}
                className={`w-12 h-14 neu-inset rounded-xl flex items-center justify-center ${
                  animating ? 'flap-animate' : ''
                }`}
              >
                <span className="text-[32px] font-bold text-accent-blue">{d}</span>
              </div>
            ))}
            <span className="text-base text-neu-text-primary font-semibold ml-1">天</span>
          </div>

          {/* 签到按钮 */}
          <div className="neu-raised rounded-2xl p-1 w-full">
            <button
              onClick={handleCheckIn}
              disabled={checkedInToday}
              className={`w-full h-12 rounded-2xl text-white font-bold text-base transition-all ${
                checkedInToday
                  ? 'neu-inset text-neu-text-muted bg-neu-bg'
                  : 'neu-accent-blue neu-interactive'
              }`}
            >
              {checkedInToday ? '今日已签到' : '立即签到'}
            </button>
          </div>
        </div>
      </div>

      {/* 活动说明卡片 */}
      <div className="mx-4 mt-4">
        <div className="neu-raised rounded-lg-card p-5">
          <h3 className="text-base font-bold text-neu-text-primary mb-3">活动说明</h3>
          <div className="neu-divider mb-3" />
          <div className="text-sm text-neu-text-secondary leading-relaxed space-y-2 font-semibold">
            <p>1. 每日签到可获得积分奖励，连续签到天数越多奖励越丰厚。</p>
            <p>2. 签到获得的积分可在积分商城兑换精美数字藏品。</p>
            <p>3. 如中途断签，连续签到天数将重新计算。</p>
            <p>4. 每人每天仅可签到一次。</p>
            <p>5. 活动最终解释权归藏锋ART平台所有。</p>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/pages/CheckInPage.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import NavBar from '@/components/common/NavBar.vue'
import { useStore } from '@/store/useStore'

const store = useStore()

const animating = ref(false)
const displayCount = ref(0)

const today = new Date().toISOString().split('T')[0]
const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0]
const checkedInToday = computed(() => store.lastCheckInDate === today)
// 是否连续签到（昨日签到过）
const isContinuous = computed(() => store.lastCheckInDate === yesterday)
// 断签时基础显示为 0（与原逻辑一致），已签到或连续时显示 store 中的天数
const baseCount = computed(() => (checkedInToday.value || isContinuous.value ? store.checkInDays : 0))

const handleCheckIn = () => {
  if (!store.isVerified) {
    store.setShowVerifyModal(true)
    return
  }
  if (animating.value || checkedInToday.value) return
  animating.value = true
  // 目标值：连续则 +1，断签则重置为 1
  const target = isContinuous.value ? store.checkInDays + 1 : 1
  let current = baseCount.value
  displayCount.value = current
  const timer = setInterval(() => {
    current += 1
    if (current >= target) {
      clearInterval(timer)
      store.checkIn()
      displayCount.value = target
      animating.value = false
      store.showToast('签到成功', 'success')
    } else {
      displayCount.value = current
    }
  }, 100)
}

// 动画中显示 displayCount，否则显示 baseCount
const count = computed(() => (animating.value ? displayCount.value : baseCount.value))
const digits = computed(() => String(count.value).padStart(3, '0').split(''))
</script>

<template>
  <div class="page-container bg-neu-bg">
    <NavBar title="签到活动" />

    <!-- 主签到卡片 -->
    <div class="mx-4 mt-4">
      <div class="neu-raised rounded-lg-card p-6 flex flex-col items-center">
        <p class="text-sm text-neu-text-muted font-semibold mb-4">
          {{ checkedInToday ? '今日已签到' : '已连续签到' }}
        </p>

        <!-- 数字翻牌计数器 -->
        <div class="flex items-center gap-2 mb-6">
          <div
            v-for="(d, i) in digits"
            :key="i"
            :class="['w-12 h-14 neu-inset rounded-xl flex items-center justify-center', animating ? 'flap-animate' : '']"
          >
            <span class="text-[32px] font-bold text-accent-blue">{{ d }}</span>
          </div>
          <span class="text-base text-neu-text-primary font-semibold ml-1">天</span>
        </div>

        <!-- 签到按钮 -->
        <div class="neu-raised rounded-2xl p-1 w-full">
          <button
            @click="handleCheckIn"
            :disabled="checkedInToday"
            :class="['w-full h-12 rounded-2xl text-white font-bold text-base transition-all', checkedInToday ? 'neu-inset text-neu-text-muted bg-neu-bg' : 'neu-accent-blue neu-interactive']"
          >
            {{ checkedInToday ? '今日已签到' : '立即签到' }}
          </button>
        </div>
      </div>
    </div>

    <!-- 活动说明卡片 -->
    <div class="mx-4 mt-4">
      <div class="neu-raised rounded-lg-card p-5">
        <h3 class="text-base font-bold text-neu-text-primary mb-3">活动说明</h3>
        <div class="neu-divider mb-3" />
        <div class="text-sm text-neu-text-secondary leading-relaxed space-y-2 font-semibold">
          <p>1. 每日签到可获得积分奖励，连续签到天数越多奖励越丰厚。</p>
          <p>2. 签到获得的积分可在积分商城兑换精美数字藏品。</p>
          <p>3. 如中途断签，连续签到天数将重新计算。</p>
          <p>4. 每人每天仅可签到一次。</p>
          <p>5. 活动最终解释权归藏锋ART平台所有。</p>
        </div>
      </div>
    </div>
  </div>
</template>
