// src/components/common/BackButton.tsx
import { useNavigate } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

interface BackButtonProps {
  onClick?: () => void;
  className?: string;
  variant?: 'white' | 'gray' | 'transparent';
}

export default function BackButton({ onClick, className = '', variant = 'white' }: BackButtonProps) {
  const navigate = useNavigate();

  const handleClick = () => {
    if (onClick) {
      onClick();
    } else {
      navigate(-1);
    }
  };

  const variantStyles = {
    white: 'neu-raised',
    gray: 'neu-inset',
    transparent: 'bg-white/20 backdrop-blur-sm',
  };

  return (
    <button
      onClick={handleClick}
      className={`w-9 h-9 rounded-full flex items-center justify-center neu-interactive ${variantStyles[variant]} ${className}`}
    >
      <ArrowLeft size={18} className="text-accent-blue" />
    </button>
  );
}

// src/components/common/BackButton.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowLeft } from 'lucide-vue-next'

const props = withDefaults(defineProps<{
  onClick?: () => void
  variant?: 'white' | 'gray' | 'transparent'
}>(), { variant: 'white' })

const router = useRouter()

const handleClick = () => {
  if (props.onClick) props.onClick()
  else router.back()
}

const variantClass = computed(() => ({
  white: 'neu-raised',
  gray: 'neu-inset',
  transparent: 'bg-white/20 backdrop-blur-sm',
}[props.variant]))
</script>

<template>
  <button
    class="w-9 h-9 rounded-full flex items-center justify-center neu-interactive"
    :class="[variantClass]"
    @click="handleClick"
  >
    <ArrowLeft :size="18" class="text-accent-blue" />
  </button>
</template>
